export const schemas = {
    newDiscount: {
        type: 'object',
        properties: {
            name: { type: 'string', isNotEmpty: true },
            code: { type: 'string', isNotEmpty: true },
            type: { type: 'string', enum: ['amount', 'percent'] },
            value: { type: 'integer' },
            enabled: { type: 'boolean' },
            start_at: { type: 'string', format: 'date-time' },
            end_at: { type: 'string', format: 'date-time' },
        },
        required: [
            'name',
            'code',
            'type',
            'value',
            'enabled',
            'start_at',
            'end_at',
        ],
        additionalProperties: false,
    },
    saveDiscount: {
        type: 'object',
        properties: {
            name: { type: 'string', isNotEmpty: true },
            code: { type: 'string', isNotEmpty: true },
            type: { type: 'string', enum: ['amount', 'percent'] },
            value: { type: 'integer' },
            enabled: { type: 'boolean' },
            start_at: { type: 'string', format: 'date-time' },
            end_at: { type: 'string', format: 'date-time' },
        },
        required: [
            'name',
            'code',
            'type',
            'value',
            'enabled',
            'start_at',
            'end_at',
        ],
        additionalProperties: false,
    },
    newProduct: {
        type: 'object',
        properties: {
            name: { type: 'string', isNotEmpty: true },
            permalink: { type: 'string', isNotEmpty: true },
            summary: { type: 'string', isNotEmpty: true },
            description: { type: 'string', isNotEmpty: true },
            price: { type: 'integer' },
            enabled: { type: 'boolean' },
        },
        required: [
            'name',
            'permalink',
            'summary',
            'description',
            'price',
            'enabled',
        ],
        additionalProperties: false,
    },
    saveProduct: {
        type: 'object',
        properties: {
            id: { type: 'string' },
            created_at: { type: 'string' },
            name: { type: 'string', isNotEmpty: true },
            permalink: { type: 'string', isNotEmpty: true },
            summary: { type: 'string', isNotEmpty: true },
            description: { type: 'string', isNotEmpty: true },
            price: { type: 'string', format: 'double' },
            enabled: { type: 'boolean' },
            variants: { type: 'array' },
        },
        required: [
            'id',
            'created_at',
            'name',
            'permalink',
            'summary',
            'description',
            'price',
            'enabled',
        ],
        additionalProperties: false,
    },
};
